services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  luke:
    build: .
    container_name: ubuntu_vnc
    environment:
      VNC_PASSWORD: StrongPassword
      HTTP_PASSWORD: SecurePassword
      # RESOLUTION: 1280x800          # <--- set screen size here
      RESOLUTION: 1920x1080
    ports:
      - "6080:80"
      - "5900:5900"
    volumes:
      - ./luke:/root/luke       # mount your luke.jar
      - ./esdata:/mnt/esdata:ro
    restart: unless-stopped

  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: desktop
    environment:
      - VNC_PASSWORD=StrongPassword
    ports:
      - "8080:80"    # for browser access
      - "5901:5900"  # for VNC client access
    depends_on:
      - luke
    command: /bin/sh -c "sleep 8 && lxterminal -e 'vncviewer ubuntu_vnc:5900 || bash'"
    # You can also install vncviewer tools if not present by overriding entrypoint




