version: "3.9"

services:
  elasticvue:
    image: cars10/elasticvue:latest
    container_name: elasticvue
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - elk-docker

networks:           # This section defines custom networks for use in a Docker Compose file.
  elk-docker:       # This is the name of the network your services will connect to.
    external: true  # Tells Docker Compose not to create this network. 
                    # It must already exist (created outside the current docker-compose.yml context).