version: "2.2"

services:
  cerebro:
    build:
      context: .
      dockerfile: Dockerfile.cerebro
    container_name: cerebro
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./cerebro.conf:/opt/cerebro/conf/application.conf
    networks:
      - elk-docker

networks:           # This section defines custom networks for use in a Docker Compose file.
  elk-docker:       # This is the name of the network your services will connect to.
    external: true  # Tells Docker Compose not to create this network. 
                    # It must already exist (created outside the current docker-compose.yml context).

