version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.4
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../../output-json/access_log.json:/usr/share/logstash/logs/log.json
    environment:
      - ELASTICSEARCH_HOST=es01
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - elk-docker

networks:
  elk-docker:
    external: true


    